services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smtpuser
      POSTGRES_PASSWORD: smtppass
      POSTGRES_DB: smtp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
volumes:
  db_data:
