package reply

type ReplyToken int

const (
	REPLY_LINE ReplyToken = iota
	GREETING
	EHLO
	OK
	SERVICE_READY
	SERVICE_CLOSING
	AUTH_SUCCESS
	AUTH_REQUIRED
	SYNTAX_ERROR
	PARAMETER_ERROR
	CMD_NOT_IMPLEMENTED
	BAD_SEQUENCE
	AUTH_FAILED
	MAILBOX_UNAVAILABLE
	INSUFFICIENT_STORAGE
	LOCAL_ERROR
	TRANSACTION_FAILED
)

var AllReplies = []ReplyToken{
	REPLY_LINE,
	GREETING,
	EHLO,
	OK,
	SERVICE_READY,
	SERVICE_CLOSING,
	AUTH_SUCCESS,
	AUTH_REQUIRED,
	SYNTAX_ERROR,
	PARAMETER_ERROR,
	CMD_NOT_IMPLEMENTED,
	BAD_SEQUENCE,
	AUTH_FAILED,
	MAILBOX_UNAVAILABLE,
	INSUFFICIENT_STORAGE,
	LOCAL_ERROR,
	TRANSACTION_FAILED,
}

func IsValidReply(reply ReplyToken) bool {
	for _, r := range AllReplies {
		if r == reply {
			return true
		}
	}
	return false
}
